name: Test
on: push
jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0
          compression: bzip
      - name: Run test suites
        run: inso run test uts_4d41bf --env UnitTest --ci
      - name: Generate declarative config
        run: inso generate config "Swagger Petstore 1.0.6" --type declarative --ci
